name: Link Checker
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: >-
          sudo apt-get install -y
          pandoc
      - uses: actions/checkout@v3
      - run: |
          find . -name '*.html' -delete
      - run: |
          find . -name '*.md' -exec pandoc -i {} -o {}.html \;
      - uses: anishathalye/proof-html@v2
        with:
          directory: .
          check_favicon: false
          check_html: false
          ignore_empty_alt: true
          ignore_url_re: |
            ^https:\/\/docs\.github\.com\/
            ^https:\/\/github\.com\/cleanlab\/cleanlab\/projects
            ^https:\/\/twitter.com\/CleanlabAI
            ^https:\/\/github.com\/cgnorthcutt\/confidentlearning-reproduce\/
            ^contrib\/
          ignore_url: |
            https://github.com/cleanlab/s/blob/master/student-grades-demo.csv
            https://github.com/cgnorthcutt/confidentlearning-reproduce/blob/master/cifar10/confidentlearning_and_coteaching/results/4_6/train_pruned_cl_pbnr/train_mask.npy
            https://raw.githubusercontent.com/cleanlab/assets/master/cleanlab/cifar10_benchmarks.png
            https://raw.githubusercontent.com/cleanlab/assets/master/cleanlab/imagenet_train_label_errors_32.jpg
            https://raw.githubusercontent.com/cleanlab/assets/master/cleanlab/mnist_training_label_errors24_prune_by_noise_rate.png
            https://raw.githubusercontent.com/cleanlab/assets/master/cleanlab/demo_cleanlab_across_datasets_and_classifiers.png
          swap_urls: |
            {"^\.\/": "https://github.com/cleanlab/examples/blob/master/"}